ALTER TABLE `QUESTION` ALTER COLUMN ID BIGINT DEFAULT NOT NULL auto_increment;
ALTER TABLE `QUESTION` ALTER COLUMN CREATOR BIGINT DEFAULT NOT NULL;
ALTER TABLE `USER` ALTER COLUMN ID BIGINT DEFAULT NOT NULL auto_increment;
ALTER TABLE `COMMENT` ALTER COLUMN COMMENTATOR BIGINT DEFAULT NOT NULL;